POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Note connected to user",
    "date": "0000000",
    "important": true,
    "userId": "61aae52420f411cec241d382"
}